### ISSUE TITLE
Add on dismiss event listener

### ISSUE THREAD

**Issue by devender-gupta** [shaack/bootstrap-show-notification#2]
Is there an event listener for dismiss?
If yes, please let me know.
If no, please add it. It would be helpful.

**Comment by shaack** [comment]
Hi, there is one. Because $.showNotification uses the bootstrap alerts you have the same API as described here: https://getbootstrap.com/docs/4.1/components/alerts/ 

It should work like this:

```
const notification = $.showNotification({ body: "Test" })

notification.$element.on('closed.bs.alert', function () {
  // do something…
})
```
